[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
dapp = "5x1PoPUPcNtR6czzvRqu49n2WMGmTYPxrN9zEVH9XpM3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node tests/dapp.js"
